### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by romant9** [Extrys/RealTimeMeshOptimizer#1]
inputTris[0] of FaceRemovalJob has Index 65536 is out of range of Vertices Count. How to use this script? Please make an example scene

**Comment by Extrys** [comment]
Right i should put an example scene, i will do this afternoon when i get time spare, you should put this script in an object with a mesh renderer and a mesh filter, then you assign all the empty fields. if this is giving error still, i will take a look

**Comment by Extrys** [comment]
Im gonna publish a new repo soon regarding  mesh optimizations in real time, and this one will be fixed and improved also
